
#ifndef BALANCEBOTPINS_H_
#define BALANCEBOTPINS_H_

//Encoder
#define PIN_ENCODER_RIGHT_A 2 //GREEN UPPER MOTOR
#define PIN_ENCODER_RIGHT_B 12 //BLUE UPPER MOTOR
#define PIN_ENCODER_LEFT_A 3 //GREEN, LOWER MOTOR
#define PIN_ENCODER_LEFT_B 13 //BLUE, LOWER MOTOR

//H-Bridge
#define PIN_HB_RIGHT_ENABLE 5 //PURPLE (ENB_A)
#define PIN_HB_LEFT_FORWARD 4 //RED (IN1)
#define PIN_HB_LEFT_BACKWARD 7 //ORANGE (IN2)
#define PIN_HB_LEFT_ENABLE 6 //GRAY (ENB_B)
#define PIN_HB_RIGHT_BACKWARD 8 //ORANGE (IN4)
#define PIN_HB_RIGHT_FORWARD 9 //RED (IN3)

#endif
